{
    "meals": [{
            "idMeal": "52770",
            "strMeal": "Spaghetti Bolognese",
            "strDrinkAlternate": null,
            "strCategory": "Beef",
            "strArea": "Italian",
            "strInstructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins. Add the garlic and mince and fry until they both brown. Add the mushrooms and herbs, and cook for another couple of mins.\r\n\r\nStir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning. Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins.\r\n\r\nMeanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions. Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce. Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
            "strTags": "Pasta,Meat",
            "strYoutube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
            "strIngredient1": "onions",
            "strIngredient2": "olive oil",
            "strIngredient3": "garlic",
            "strIngredient4": "lean minced beef",
            "strIngredient5": "mushrooms",
            "strIngredient6": "dried oregano",
            "strIngredient7": "tomatoes",
            "strIngredient8": "hot beef stock",
            "strIngredient9": "tomato puree",
            "strIngredient10": "worcestershire sauce",
            "strIngredient11": "spaghetti",
            "strIngredient12": "parmesan",
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "2",
            "strMeasure2": "1tbsp",
            "strMeasure3": "1 clove",
            "strMeasure4": "500g",
            "strMeasure5": "90g",
            "strMeasure6": "1tsp",
            "strMeasure7": "400g can",
            "strMeasure8": "300ml",
            "strMeasure9": "1tbsp",
            "strMeasure10": "1tbsp",
            "strMeasure11": "350g",
            "strMeasure12": "Topping",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52771",
            "strMeal": "Spicy Arrabiata Penne",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "Italian",
            "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
            "strTags": "Pasta,Curry",
            "strYoutube": "https://www.youtube.com/watch?v=1IszT_guI08",
            "strIngredient1": "penne rigate",
            "strIngredient2": "olive oil",
            "strIngredient3": "garlic",
            "strIngredient4": "chopped tomatoes",
            "strIngredient5": "red chile flakes",
            "strIngredient6": "italian seasoning",
            "strIngredient7": "basil",
            "strIngredient8": "Parmigiano-Reggiano",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "1 pound",
            "strMeasure2": "1/4 cup",
            "strMeasure3": "3 cloves",
            "strMeasure4": "1 tin ",
            "strMeasure5": "1/2 teaspoon",
            "strMeasure6": "1/2 teaspoon",
            "strMeasure7": "6 leaves",
            "strMeasure8": "spinkling",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52784",
            "strMeal": "Smoky Lentil Chili with Squash",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "British",
            "strInstructions": "Begin by roasting the squash. Slice it into thin crescents and drizzle with a little oil and sprinkle with sea salt. I added a fresh little sage I had in the fridge, but it’s unnecessary. Roast the squash a 205 C (400 F) for 20-30 minutes, flipping halfway through, until soft and golden. Let cool and chop into cubes.\r\nMeanwhile, rinse the lentils and cover them with water. Bring them to the boil then turn down to a simmer and let cook (uncovered) for 20-30 minutes, or until tender. Drain and set aside.\r\nWhile the lentils are cooking heat the 1 Tbsp. of oil on low in a medium pot. Add the onions and leeks and sauté for 5 or so minutes, or until they begin to soften. Add the garlic next along with the cumin and coriander, cooking for a few more minutes. Add the remaining spices – paprika, cinnamon, chilli, cocoa, Worcestershire sauce, salt, and oregano. Next add the can of tomatoes, the water or stock, and carrots. Let simmer, covered, for 20 minutes or until the veg is tender and the mixture has thickened up. You’ll need to check on the pot periodically for a stir and a top of of liquid if needed.\r\nAdd the lentils and chopped roasted squash. Let cook for 10 more minutes to heat through.\r\nServe with sliced jalapeno, lime wedges, cilantro, green onions, and cashew sour cream.\r\n\r\nSIMPLE CASHEW SOUR CREAM\r\n\r\n1 Cup Raw Unsalted Cashews\r\nPinch Sea Salt\r\n1 tsp. Apple Cider Vinegar\r\nWater\r\n\r\nBring some water to the boil, and use it to soak the cashews for at least four hours. Alternatively, you can use cold water and let the cashews soak overnight, but I’m forgetful/lazy, so often use the boil method which is much faster.\r\nAfter the cashews have soaked, drain them and add to a high speed blender. Begin to puree, slowly adding about 1/2 cup fresh water, until a creamy consistency is reached. You may need to add less or more water to reach the desired consistency.\r\nAdd a pinch of sea salt and vinegar (or lemon juice).",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg",
            "strTags": "Pulse",
            "strYoutube": "https://www.youtube.com/watch?v=pKmqawK2Tqs",
            "strIngredient1": "Olive Oil",
            "strIngredient2": "Onion",
            "strIngredient3": "Leek",
            "strIngredient4": "Garlic",
            "strIngredient5": "Cumin",
            "strIngredient6": "Coriander",
            "strIngredient7": "Smoked Paprika",
            "strIngredient8": "Cinnamon",
            "strIngredient9": "Chili Powder",
            "strIngredient10": "Cocoa",
            "strIngredient11": "Dried Oregano",
            "strIngredient12": "Diced Tomatoes",
            "strIngredient13": "Water",
            "strIngredient14": "Carrots",
            "strIngredient15": "Brown Lentils",
            "strIngredient16": "Sea Salt",
            "strIngredient17": "Squash",
            "strIngredient18": "Cashews",
            "strIngredient19": "Apple Cider Vinegar",
            "strIngredient20": "",
            "strMeasure1": "1 tbls",
            "strMeasure2": "1",
            "strMeasure3": "1 chopped",
            "strMeasure4": "3 cloves",
            "strMeasure5": "4 tsp ground ",
            "strMeasure6": "2 tsp ground",
            "strMeasure7": "1 tsp",
            "strMeasure8": "1/2 tsp",
            "strMeasure9": "1 tsp",
            "strMeasure10": "1 tsp",
            "strMeasure11": "1/2 tsp",
            "strMeasure12": "1 can",
            "strMeasure13": "3 cups",
            "strMeasure14": "3 chopped",
            "strMeasure15": "1 1/2 cups",
            "strMeasure16": "1 tsp",
            "strMeasure17": "1 Small",
            "strMeasure18": "1 Cup",
            "strMeasure19": "1 tsp",
            "strMeasure20": "",
            "strSource": "http://www.wholeheartedeats.com/2016/11/smoky-lentil-chili-squash/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52793",
            "strMeal": "Sticky Toffee Pudding Ultimate",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "British",
            "strInstructions": "Stone and chop the dates quite small, put them in a bowl, then pour the boiling water over. Leave for about 30 mins until cool and well-soaked, then mash a bit with a fork. Stir in the vanilla extract. Butter and flour seven mini pudding tins (each about 200ml/7fl oz) and sit them on a baking sheet. Heat oven to 180C/fan 160C/gas 4.\r\nWhile the dates are soaking, make the puddings. Mix the flour and bicarbonate of soda together and beat the eggs in a separate bowl. Beat the butter and sugar together in a large bowl for a few mins until slightly creamy (the mixture will be grainy from the sugar). Add the eggs a little at a time, beating well between additions. Beat in the black treacle then, using a large metal spoon, gently fold in one-third of the flour, then half the milk, being careful not to overbeat. Repeat until all the flour and milk is used. Stir the soaked dates into the pudding batter. The mix may look a little curdled at this point and will be like a soft, thick batter. Spoon it evenly between the tins and bake for 20-25 mins, until risen and firm.\r\nMeanwhile, put the sugar and butter for the sauce in a medium saucepan with half the cream. Bring to the boil over a medium heat, stirring all the time, until the sugar has completely dissolved. Stir in the black treacle, turn up the heat slightly and let the mixture bubble away for 2-3 mins until it is a rich toffee colour, stirring occasionally to make sure it doesn’t burn. Take the pan off the heat and beat in the rest of the cream.\r\nRemove the puddings from the oven. Leave in the tins for a few mins, then loosen them well from the sides of the tins with a small palette knife before turning them out. You can serve them now with the sauce drizzled over, but they’ll be even stickier if left for a day or two coated in the sauce. To do this, pour about half the sauce into one or two ovenproof serving dishes. Sit the upturned puddings on the sauce, then pour the rest of the sauce over them. Cover with a loose tent of foil so that the sauce doesn’t smudge (no need to chill).\r\nWhen ready to serve, heat oven to 180C/fan 160C/gas 4. Warm the puddings through, still covered, for 15-20 mins or until the sauce is bubbling. Serve them on their own, or with cream or custard.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg",
            "strTags": "Pudding,Desert,Cake,Dairy",
            "strYoutube": "https://www.youtube.com/watch?v=hKq6RbxJHBo",
            "strIngredient1": "Medjool dates",
            "strIngredient2": "water",
            "strIngredient3": "vanilla extract",
            "strIngredient4": "self-raising flour",
            "strIngredient5": "bicarbonate of soda",
            "strIngredient6": "eggs",
            "strIngredient7": "butter",
            "strIngredient8": "demerara sugar",
            "strIngredient9": "black treacle",
            "strIngredient10": "milk",
            "strIngredient11": "ice cream",
            "strIngredient12": "muscovado sugar",
            "strIngredient13": "butter",
            "strIngredient14": "double cream",
            "strIngredient15": "black treacle",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "225g",
            "strMeasure2": "175ml Boiling",
            "strMeasure3": "1 tsp",
            "strMeasure4": "175g",
            "strMeasure5": "1 tsp",
            "strMeasure6": "2",
            "strMeasure7": "85g",
            "strMeasure8": "140g",
            "strMeasure9": "2 tbsp",
            "strMeasure10": "100ml",
            "strMeasure11": "1 scoop",
            "strMeasure12": "175g",
            "strMeasure13": "50g",
            "strMeasure14": "225ml",
            "strMeasure15": "1 tbsp",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.youtube.com/watch?v=Wytv3bjqJII",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52797",
            "strMeal": "Spicy North African Potato Salad",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "Moroccan",
            "strInstructions": "Cook potatoes - place potatoes in a pot of cold water, and bring to the boil. Boil 20 minutes, or until potatoes are tender. You know they are cooked when you can stick a knife in them and the knife goes straight through.\r\nCombine harissa spice, olive oil, salt and pepper and lemon juice in a small bowl and whisk until combined.\r\nOnce potatoes are cooked, drain water and roughly chop potatoes in half.\r\nAdd harissa mix and spring onions/green onions to potatoes and stir.\r\nIn a large salad bowl, lay out arugula/rocket.\r\nTop with potato mix and toss.\r\nAdd fetta, mint and sprinkle over pine nuts.\r\nAdjust salt and pepper to taste.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg",
            "strTags": "Vegetarian,Spicy",
            "strYoutube": "https://www.youtube.com/watch?v=zxBzwJvTK4g",
            "strIngredient1": "Small Potatoes",
            "strIngredient2": "Harissa Spice",
            "strIngredient3": "olive oil",
            "strIngredient4": "Lemon",
            "strIngredient5": "Spring onions",
            "strIngredient6": "Rocket",
            "strIngredient7": "Feta",
            "strIngredient8": "Mint",
            "strIngredient9": "Pine nuts",
            "strIngredient10": "Salt",
            "strIngredient11": "Pepper",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "650g/1lb 8 oz",
            "strMeasure2": "1 tsp",
            "strMeasure3": "2 tsp",
            "strMeasure4": "juice of half",
            "strMeasure5": "4",
            "strMeasure6": "150g/6oz",
            "strMeasure7": "80g/3oz",
            "strMeasure8": "20 chopped",
            "strMeasure9": "2 tablespoons",
            "strMeasure10": "Pinch",
            "strMeasure11": "Pinch",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52817",
            "strMeal": "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "American",
            "strInstructions": "Heat the oil in a 12-inch skillet over high heat until shimmering. Add the eggplants and lower the heat to medium. Season with salt and pepper as you rotate the eggplants, browning them on all sides. Continue to cook, turning regularly, until a fork inserted into the eggplant meets no resistance (you may have to stand them up on their fat end to finish cooking the thickest parts), about 20 minutes, lowering the heat and sprinkling water into the pan as necessary if the eggplants threaten to burn or smoke excessively.\r\n\r\n2.\r\nMix the harissa, chickpeas and tomatoes together, then add to the eggplants. Cook until the tomatoes have blistered and broken down, about 5 minutes more. Season with salt and pepper and add water as necessary to thin to a saucy consistency. Meanwhile, combine the yogurt and cumin in a serving bowl. Season with salt and pepper.\r\n\r\n3.\r\nTop the eggplant mixture with the parsley, drizzle with more extra virgin olive oil, and serve with the yogurt on the side.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/yqwtvu1487426027.jpg",
            "strTags": "Vegetarian",
            "strYoutube": "https://www.youtube.com/watch?v=uYB-1xJp4lg",
            "strIngredient1": "Olive Oil",
            "strIngredient2": "Egg Plants",
            "strIngredient3": "Harissa",
            "strIngredient4": "Chickpeas",
            "strIngredient5": "Cherry Tomatoes",
            "strIngredient6": "Greek yogurt",
            "strIngredient7": "Ground cumin",
            "strIngredient8": "Parsley",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "4 tablespoons",
            "strMeasure2": "6 small",
            "strMeasure3": "½ tablespoon",
            "strMeasure4": "1 can",
            "strMeasure5": "2 cups halved",
            "strMeasure6": "1 1/2 cups",
            "strMeasure7": "1 tablespoon",
            "strMeasure8": "½ cup ",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.seriouseats.com/2014/09/one-pot-wonders-stovetop-eggplant-harissa-chickpeas-cumin.html",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52823",
            "strMeal": "Salmon Prawn Risotto",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Italian",
            "strInstructions": "Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\r\nAdd the rice and stir to coat all the grains in the butter\r\nAdd the wine and cook gently stirring until it is absorbed\r\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\r\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\r\nServe scattered with the Parmesan and seasonal vegetables.\r\nGrill the salmon and gently place onto the risotto with the prawns and asparagus",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
            "strTags": "Fish",
            "strYoutube": "https://www.youtube.com/watch?v=V2PMvBv52IE",
            "strIngredient1": "butter",
            "strIngredient2": "onion",
            "strIngredient3": "rice",
            "strIngredient4": "white wine",
            "strIngredient5": "vegetable stock",
            "strIngredient6": "lemon",
            "strIngredient7": "King Prawns",
            "strIngredient8": "salmon",
            "strIngredient9": "asparagus",
            "strIngredient10": "black pepper",
            "strIngredient11": "Parmesan",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "50g/2oz",
            "strMeasure2": "1 finely chopped ",
            "strMeasure3": "150g",
            "strMeasure4": "125ml ",
            "strMeasure5": "1 litre hot",
            "strMeasure6": "The juice and zest of one",
            "strMeasure7": "240g large",
            "strMeasure8": "150g",
            "strMeasure9": "100g tips blanched briefly in boiling water",
            "strMeasure10": "ground",
            "strMeasure11": "50g shavings",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        },
        {
            "idMeal": "52833",
            "strMeal": "Salted Caramel Cheescake",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "American",
            "strInstructions": "1) Blitz the biscuits and the pretzels in a food processor and mix the biscuits with the melted butter. Spread on the bottom of an 8″/20cm Deep Springform Tin and press down firmly. Leave to set in the fridge whilst you make the rest!\r\n\r\n2) Using an electric mixer, I use my KitchenAid with the whisk attachment, whisk together the cream cheese, vanilla, and icing sugar until smooth and then add the caramel and whisk again until smooth and lump free – this could take a couple of minutes, I whisk it at half speed so not too quick or slow!\r\n\r\n3) Pour in the double cream & Salt flakes and continue to whisk for a couple of minutes until its very thick and mousse like (I mix it on a medium speed, level 6/10) – Now this could take up to 5 minutes depending on your mixer, but you seriously have to stick at it – it will hold itself completely when finished mixing (like a meringue does!) If you don’t mix it enough it will not set well enough, but don’t get impatient and whisk it really quick because that’ll make it split! Spread over the biscuit base and leave to set in the fridge overnight.\r\n\r\n4) Remove the Cheesecake from the tin carefully and decorate the cheesecake – I drizzled over some of the spare caramel, and then some Toffee Popcorn and more Pretzels!",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xqrwyr1511133646.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=q5dQp3qpmI4",
            "strIngredient1": "Digestive Biscuits",
            "strIngredient2": "Pretzels",
            "strIngredient3": "Butter",
            "strIngredient4": "Cream Cheese",
            "strIngredient5": "Vanilla Extract",
            "strIngredient6": "Icing Sugar",
            "strIngredient7": "Caramel",
            "strIngredient8": "Sea Salt",
            "strIngredient9": "Double Cream",
            "strIngredient10": "Caramel Sauce",
            "strIngredient11": "Toffee Popcorn",
            "strIngredient12": "Pretzels",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "250g",
            "strMeasure2": "75g",
            "strMeasure3": "135g",
            "strMeasure4": "450g",
            "strMeasure5": "1tsp",
            "strMeasure6": "100g ",
            "strMeasure7": "150g",
            "strMeasure8": "1tsp",
            "strMeasure9": "300ml ",
            "strMeasure10": "drizzle",
            "strMeasure11": "Top",
            "strMeasure12": "Top",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.janespatisserie.com/2015/11/09/no-bake-salted-caramel-cheesecake/",
            "strImageSource": null,
            "strCreativeCommonsConfirmed": null,
            "dateModified": null
        }
    ]
}